platform :ios, '16.0'

inhibit_all_warnings!

target 'MishuApp' do
  use_frameworks! :linkage => :static

  # 友盟统计 + U-APM（包含崩溃监控）
  pod 'UMCommon'
  pod 'UMDevice'
  pod 'UMAPM'
  pod 'WechatOpenSDK-XCFramework'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
